Repository code-is-evenly-cooked/even-IDE-back, pull requests merged in 2025-04, with the labels that each got.

#1 docs: PR template 추가
  docs/pull_request_template.md
Labels: documentation

#2 config : 프로젝트 기본 세팅
  .gitattributes
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/evenly/evenide/EvenideApplication.java
  src/main/resources/application.properties
  src/test/java/com/evenly/evenide/EvenideApplicationTests.java
Labels: 🔧configuration

#3 도커 등 코드 수정 (CICD 작동하는지 테스트)
  Dockerfile
  docker-compose.yml
  docs/pull_request_template.md
  src/main/resources/application.properties
Labels: 🐛bug, 📝documentation, 🔧configuration

#4 목업 API 추가
  build.gradle
  src/main/java/com/evenly/evenide/Config/Security/SecurityConfig.java
  src/main/java/com/evenly/evenide/Config/WebConfig.java
  src/main/java/com/evenly/evenide/mock/HealthCheck.java
  src/main/java/com/evenly/evenide/mock/MockAuthController.java
  src/main/java/com/evenly/evenide/mock/MockCodeController.java
  src/main/java/com/evenly/evenide/mock/MockFileController.java
Labels: ✨feature, 🔧configuration

#5 hotfix: 목업 파일 불러오기 - 불필요 코드 삭제, pathvariable 버그 수정
  src/main/java/com/evenly/evenide/mock/MockFileController.java
Labels: 🐛bug

#6 회원가입 API 및 이메일/닉네임 중복 확인 기능 구현
  src/main/java/com/evenly/evenide/EvenideApplication.java
  src/main/java/com/evenly/evenide/controller/AuthController.java
  src/main/java/com/evenly/evenide/dto/SignUpDto.java
  src/main/java/com/evenly/evenide/dto/SignUpResponse.java
  src/main/java/com/evenly/evenide/entity/User.java
  src/main/java/com/evenly/evenide/global/exception/CustomException.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
  src/main/java/com/evenly/evenide/global/exception/GlobalExceptionHandler.java
  src/main/java/com/evenly/evenide/global/response/MessageResponse.java
  src/main/java/com/evenly/evenide/repository/UserRepository.java
  src/main/java/com/evenly/evenide/service/AuthService.java
Labels: ✨feature

#8 목업 API 응답, 엔드포인트 수정
  src/main/java/com/evenly/evenide/mock/HealthCheck.java
  src/main/java/com/evenly/evenide/mock/MockAuthController.java
  src/main/java/com/evenly/evenide/mock/MockCodeController.java
  src/main/java/com/evenly/evenide/mock/MockFileController.java
Labels: 🐛bug

#9 회원가입 닉네임 중복 방지 예외 추가
  src/main/java/com/evenly/evenide/Config/Security/SecurityConfig.java
  src/main/java/com/evenly/evenide/entity/User.java
  src/main/java/com/evenly/evenide/service/AuthService.java
Labels: 🐛bug

#11 로그인 API 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/evenly/evenide/Config/Security/JwtUtil.java
  src/main/java/com/evenly/evenide/controller/AuthController.java
  src/main/java/com/evenly/evenide/dto/JwtUserInfoDto.java
  src/main/java/com/evenly/evenide/dto/SignInDto.java
  src/main/java/com/evenly/evenide/dto/SignUpDto.java
  src/main/java/com/evenly/evenide/entity/RefreshToken.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
  src/main/java/com/evenly/evenide/repository/RefreshTokenRepository.java
  src/main/java/com/evenly/evenide/service/AuthService.java
  src/main/resources/application.properties
Labels: ✨feature

#12 JwtFilter 추가 및 코드 수정
  src/main/java/com/evenly/evenide/Config/Security/JwtFilter.java
  src/main/java/com/evenly/evenide/Config/Security/JwtUtil.java
  src/main/java/com/evenly/evenide/Config/Security/SecurityConfig.java
  src/main/java/com/evenly/evenide/controller/AuthController.java
  src/main/java/com/evenly/evenide/dto/SignUpDto.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
Labels: 🐛bug, ✨feature

#14 프로젝트, 코드 파일 편집 API 구현
  src/main/java/com/evenly/evenide/Config/Security/JwtFilter.java
  src/main/java/com/evenly/evenide/Config/Security/JwtUtil.java
  src/main/java/com/evenly/evenide/Config/Security/SecurityConfig.java
  src/main/java/com/evenly/evenide/controller/FileController.java
  src/main/java/com/evenly/evenide/controller/ProjectController.java
  src/main/java/com/evenly/evenide/dto/CodeUpdateRequestDto.java
  src/main/java/com/evenly/evenide/dto/EditorFileResponse.java
  src/main/java/com/evenly/evenide/dto/FileRequestDto.java
  src/main/java/com/evenly/evenide/dto/FileResponse.java
  src/main/java/com/evenly/evenide/dto/ProjectRequestDto.java
  src/main/java/com/evenly/evenide/dto/ProjectResponse.java
  src/main/java/com/evenly/evenide/entity/CodeFile.java
  src/main/java/com/evenly/evenide/entity/Project.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
  src/main/java/com/evenly/evenide/repository/CodeFileRepository.java
  src/main/java/com/evenly/evenide/repository/ProjectRepository.java
  src/main/java/com/evenly/evenide/service/FileService.java
  src/main/java/com/evenly/evenide/service/ProjectService.java
Labels: 🐛bug, ✨feature, 🔧configuration

#15 파일, 코드 수정 잠금/해제 API 구현
  src/main/java/com/evenly/evenide/controller/FileController.java
  src/main/java/com/evenly/evenide/dto/EditorFileResponse.java
  src/main/java/com/evenly/evenide/entity/CodeFile.java
  src/main/java/com/evenly/evenide/service/FileService.java
Labels: 🐛bug, ✨feature

#16 마이페이지, 비밀번호 변경 및 로그아웃 API 구현
  build.gradle
  src/main/java/com/evenly/evenide/Config/RedisConfig.java
  src/main/java/com/evenly/evenide/Config/Security/JwtUtil.java
  src/main/java/com/evenly/evenide/controller/AuthController.java
  src/main/java/com/evenly/evenide/controller/UserController.java
  src/main/java/com/evenly/evenide/dto/PasswordUpdateDto.java
  src/main/java/com/evenly/evenide/dto/UserResponseDto.java
  src/main/java/com/evenly/evenide/entity/User.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
  src/main/java/com/evenly/evenide/service/AuthService.java
Labels: ✨feature, 🔧configuration

#17 코드 실행 API 구현
  docker-compose.yml
  src/main/java/com/evenly/evenide/Config/AppConfig.java
  src/main/java/com/evenly/evenide/Config/Security/SecurityConfig.java
  src/main/java/com/evenly/evenide/controller/CodeRunController.java
  src/main/java/com/evenly/evenide/controller/FileController.java
  src/main/java/com/evenly/evenide/dto/CodeExecutionRequestDto.java
  src/main/java/com/evenly/evenide/dto/CodeExecutionResponse.java
  src/main/java/com/evenly/evenide/service/CodeRunService.java
  src/main/java/com/evenly/evenide/service/FileService.java
Labels: ✨feature, 🔧configuration

#18 비밀번호 재설정 API 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/evenly/evenide/controller/AuthController.java
  src/main/java/com/evenly/evenide/dto/EmailRequestDto.java
  src/main/java/com/evenly/evenide/dto/PasswordResetRequestDto.java
  src/main/java/com/evenly/evenide/entity/PasswordResetToken.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
  src/main/java/com/evenly/evenide/repository/PasswordResetTokenRepository.java
  src/main/java/com/evenly/evenide/service/AuthService.java
  src/main/java/com/evenly/evenide/service/EmailService.java
  src/main/resources/application.properties
Labels: ✨feature, 🔧configuration

#19 hotfix 로그인 응답 요청사항 수정
  src/main/java/com/evenly/evenide/controller/AuthController.java
  src/main/java/com/evenly/evenide/dto/SignInResponse.java
  src/main/java/com/evenly/evenide/service/AuthService.java
Labels: 🐛bug

#20 채팅 메시지 전송 웹소켓 및 채팅방 입장, 이전 채팅 조회 API 구현
  build.gradle
  src/main/java/com/evenly/evenide/EvenideApplication.java
  src/main/java/com/evenly/evenide/config/AppConfig.java
  src/main/java/com/evenly/evenide/config/RedisConfig.java
  src/main/java/com/evenly/evenide/config/WebConfig.java
  src/main/java/com/evenly/evenide/config/WebSocketConfig.java
  src/main/java/com/evenly/evenide/config/security/JwtFilter.java
  src/main/java/com/evenly/evenide/config/security/JwtUtil.java
  src/main/java/com/evenly/evenide/config/security/SecurityConfig.java
  src/main/java/com/evenly/evenide/controller/AuthController.java
  src/main/java/com/evenly/evenide/controller/ChatApiController.java
  src/main/java/com/evenly/evenide/controller/ChatController.java
  src/main/java/com/evenly/evenide/controller/UserController.java
  src/main/java/com/evenly/evenide/dto/ChatEnterRequestDto.java
  src/main/java/com/evenly/evenide/dto/ChatJoinResponse.java
  src/main/java/com/evenly/evenide/dto/ChatMessage.java
  src/main/java/com/evenly/evenide/global/scheduler/RedisChatCleaner.java
  src/main/java/com/evenly/evenide/global/util/RandomNameGenerator.java
  src/main/java/com/evenly/evenide/service/AuthService.java
  src/main/java/com/evenly/evenide/service/ChatService.java
  src/main/resources/static/chat-test.html
Labels: ✨feature

#21 Feat/live code
  src/main/java/com/evenly/evenide/config/security/SecurityConfig.java
  src/main/java/com/evenly/evenide/controller/ChatApiController.java
  src/main/java/com/evenly/evenide/controller/ChatWebSocketController.java
  src/main/java/com/evenly/evenide/controller/CodeEditorWebSocketController.java
  src/main/java/com/evenly/evenide/dto/ChatEnterRequestDto.java
  src/main/java/com/evenly/evenide/dto/ChatJoinResponse.java
  src/main/java/com/evenly/evenide/dto/CodeCursorMessage.java
  src/main/java/com/evenly/evenide/dto/CodeDiffMessage.java
  src/main/java/com/evenly/evenide/dto/CodeUpdateMessage.java
  src/main/java/com/evenly/evenide/service/CodeSyncService.java
  src/main/resources/static/chat-and-editor.html
  src/main/resources/static/chat-diff-and-cursor.html
Labels: 🐛bug, ✨feature

#22 메시지 검색 및 앞뒤 컨텍스트 메시지 조회 API 구현
  src/main/java/com/evenly/evenide/controller/ChatApiController.java
  src/main/java/com/evenly/evenide/service/ChatService.java
  src/main/resources/static/chat-diff-and-cursor.html
Labels: 🐛bug, ✨feature

#23 채팅 메시지 필터링 로직 구현
  build.gradle
  src/main/java/com/evenly/evenide/global/util/ChatMessageSanitizer.java
  src/main/java/com/evenly/evenide/service/ChatService.java
Labels: ✨feature

#25 AI API 구현
  build.gradle
  docker-compose.yml
  src/main/java/com/evenly/evenide/config/AiConfig.java
  src/main/java/com/evenly/evenide/controller/AiController.java
  src/main/java/com/evenly/evenide/dto/AiRequest.java
  src/main/java/com/evenly/evenide/dto/AiResponse.java
  src/main/java/com/evenly/evenide/service/AiService.java
  src/main/resources/application.properties
Labels: ✨feature

#27 비밀번호 재설정 유효시간 변경
  src/main/java/com/evenly/evenide/service/AuthService.java
  src/main/java/com/evenly/evenide/service/EmailService.java
Labels: 🐛bug

#29 리팩토링 및 웹 소켓 채팅 입장 메시지 타임스탬프 추가
  src/main/java/com/evenly/evenide/service/ChatService.java
Labels: 🐛bug

#28 소셜 로그인 API 구현
  src/main/java/com/evenly/evenide/controller/OAuthController.java
  src/main/java/com/evenly/evenide/dto/GoogleUserInfo.java
  src/main/java/com/evenly/evenide/dto/KakaoUserInfo.java
  src/main/java/com/evenly/evenide/dto/OAuthTokenRequestDto.java
  src/main/java/com/evenly/evenide/dto/OAuthUserInfo.java
  src/main/java/com/evenly/evenide/entity/User.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
  src/main/java/com/evenly/evenide/global/oauth/GoogleOAuthClient.java
  src/main/java/com/evenly/evenide/global/oauth/KakaoOAuthClient.java
  src/main/java/com/evenly/evenide/global/util/SocialNameGenerator.java
  src/main/java/com/evenly/evenide/repository/UserRepository.java
  src/main/java/com/evenly/evenide/service/AuthService.java
  src/main/java/com/evenly/evenide/service/OAuthService.java
Labels: ✨feature

#31 채팅 history 버그 수정
  docker-compose.yml
Labels: 🐛bug

#24 메모 API 구현 (수정되었습니다.)
  src/main/java/com/evenly/evenide/controller/MemoController.java
  src/main/java/com/evenly/evenide/dto/MemoRequest.java
  src/main/java/com/evenly/evenide/dto/MemoResponse.java
  src/main/java/com/evenly/evenide/entity/Memo.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
  src/main/java/com/evenly/evenide/repository/CodeFileRepository.java
  src/main/java/com/evenly/evenide/repository/MemoRepository.java
  src/main/java/com/evenly/evenide/service/AuthService.java
  src/main/java/com/evenly/evenide/service/MemoService.java
Labels: ✨feature

#32 [hotfix] HTTPS 변경으로 ngrok 도메인 ws, cors 부분 추가
  src/main/java/com/evenly/evenide/config/WebConfig.java
  src/main/java/com/evenly/evenide/config/WebSocketConfig.java
  src/main/java/com/evenly/evenide/config/security/SecurityConfig.java
Labels: 🐛bug

#33 커스텀 에러 코드 ; , 오타 수정
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
Labels: 🐛bug

#34 [hotfix] cors 버그 수정
  src/main/java/com/evenly/evenide/config/WebConfig.java
  src/main/java/com/evenly/evenide/config/WebSocketConfig.java
Labels: 🐛bug

#35 cors 에러 해결 시도
  src/main/java/com/evenly/evenide/config/WebConfig.java
Labels: 🐛bug

#38 메모 기능 관련 심각한 버그 수정
  src/main/java/com/evenly/evenide/entity/Memo.java
  src/main/java/com/evenly/evenide/global/exception/ErrorCode.java
  src/main/java/com/evenly/evenide/repository/MemoRepository.java
  src/main/java/com/evenly/evenide/service/MemoService.java
Labels: 🐛bug
